version: 2

env:
  - GO111MODULE=on

release:
  # Only create GitHub releases for semantic version tags (v*)
  # Disable for pr-* and sha-* tags
  disable: '{{ if hasPrefix .Tag "v" }}false{{ else }}true{{ end }}'
  draft: false
  prerelease: auto

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X go.pixelfactory.io/pkg/version.REVISION={{ .ShortCommit }}
      - -X go.pixelfactory.io/pkg/version.BUILDDATE={{ .CommitDate }}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
      - go mod tidy

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/pixelfactoryio/crashlooper
    description: |-
      A simple container that crash 💥 after a set amount of time ⏰.
    maintainer: Amine Benseddik <amine@pixelfactory.io>
    license: MIT
    vendor: pixelfactory.io
    formats:
      - apk
      - deb
      - rpm

dockers:
  - image_templates:
      - "pixelfactory/crashlooper:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "pixelfactory/crashlooper:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "pixelfactory/crashlooper:{{ .Version }}"
    image_templates:
      - "pixelfactory/crashlooper:{{ .Version }}-amd64"
      - "pixelfactory/crashlooper:{{ .Version }}-arm64"
    skip_push: false
  - name_template: "pixelfactory/crashlooper:latest"
    image_templates:
      - "pixelfactory/crashlooper:{{ .Version }}-amd64"
      - "pixelfactory/crashlooper:{{ .Version }}-arm64"
    skip_push: auto

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
      - zip
    files:
      - LICENSE
      - README.md
